version: "3.9"
services:
  frontend:
    container_name: frontend-nextjs
    build: .
    ports:
      - "3000:3000"
    links:
      - database
    volumes:
      - .:/home/app/
  database:
    container_name: postgres-db
    restart: on-failure
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: ecommerce-database
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
