name: CI/CD Pipeline for Dev PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      # 1. Instalar dependencias
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm install

      # 2. Lint
      - name: Run Lint
        run: npm run lint

      # 4. Ejecutar tests
      - name: Run Tests
        run: npm test


      # 6. Revisar vulnerabilidades
      - name: Check for Vulnerabilities
        run: npm audit

      # 7. Construir el proyecto
      - name: Build Project
        run: npm run build